export const data = [
  {
    _id: "5f5b32e0212acbe7a1af1d46",
    index: 0,
    guid: "dff6d4b9-eb49-46bf-ba60-cb1216f9f129",
    isActive: false,
    balance: "€1,555",
    personal: "2 / 8",
    picture: "http://placehold.it/32x32",
    age: 40,
    eyeColor: "green",
    name: "Bates Benjamin",
    gender: "male",
    company: "COMDOM",
    email: "batesbenjamin@comdom.com",
    phone: "+1 (885) 509-2505",
    address: "486 Powers Street, Belmont, Wyoming, 2939",
    about:
      "Pariatur exercitation ea veniam incididunt occaecat. Enim reprehenderit eu aliquip fugiat sit excepteur deserunt commodo veniam minim laborum. Aliqua ad minim consequat occaecat proident voluptate magna excepteur do. Culpa sit aliquip in non. Ea ullamco mollit aliquip est mollit aute non excepteur commodo do ullamco incididunt. Dolore culpa amet exercitation veniam aliqua non incididunt ullamco mollit duis ullamco deserunt.\r\n",
    registered: "2020-07-30",
    latitude: -86.947693,
    longitude: -152.878072,
    tags: ["elit", "nisi", "velit", "tempor", "irure", "enim", "eu"],
    friends: [
      {
        id: 0,
        name: "Santana Griffin",
      },
      {
        id: 1,
        name: "Solomon Henderson",
      },
      {
        id: 2,
        name: "Katharine Patton",
      },
    ],
    greeting: "Hello, Bates Benjamin! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "5f5b32e0b52d7b6588a2a38e",
    index: 1,
    guid: "a6a8740c-dca5-43b4-9bea-8f2bfcd058fe",
    isActive: true,
    balance: "€1,094",
    personal: "7 / 8",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "brown",
    name: "Heather Livingston",
    gender: "female",
    company: "PLASMOSIS",
    email: "heatherlivingston@plasmosis.com",
    phone: "+1 (966) 477-3243",
    address: "322 Montague Terrace, Lowell, Palau, 7622",
    about:
      "Adipisicing velit commodo cillum esse voluptate officia fugiat commodo fugiat proident excepteur nostrud officia consectetur. Anim pariatur eiusmod magna ipsum qui adipisicing. Deserunt dolor quis officia mollit non. Aliquip ea do est pariatur eu officia magna sunt cupidatat deserunt. Eu in do nostrud aliquip deserunt sint mollit officia nulla. Nostrud ut officia eiusmod elit. Laborum ea velit Lorem mollit laboris est Lorem nisi voluptate adipisicing anim dolore.\r\n",
    registered: "2020-03-17",
    latitude: -8.321619,
    longitude: 23.635911,
    tags: [
      "irure",
      "mollit",
      "mollit",
      "id",
      "consequat",
      "velit",
      "exercitation",
    ],
    friends: [
      {
        id: 0,
        name: "Silvia Carpenter",
      },
      {
        id: 1,
        name: "Juanita Figueroa",
      },
      {
        id: 2,
        name: "Bertie Joyce",
      },
    ],
    greeting: "Hello, Heather Livingston! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "5f5b32e0efd2b7cb135a163f",
    index: 2,
    guid: "ece836f7-6f18-4039-80af-aac21c16b708",
    isActive: false,
    balance: "€3,890",
    personal: "7 / 8",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "brown",
    name: "Amy Villarreal",
    gender: "female",
    company: "BUNGA",
    email: "amyvillarreal@bunga.com",
    phone: "+1 (887) 449-2167",
    address: "516 Prospect Street, Siglerville, Kansas, 2933",
    about:
      "Ad elit officia laborum magna sit ad. Tempor exercitation ad irure culpa commodo. Fugiat nostrud laboris ea excepteur duis ex in est. Laborum sunt esse eu occaecat. Labore ullamco eiusmod id sint dolor minim consectetur laborum ex. Sint esse et laboris ut voluptate qui mollit cupidatat.\r\n",
    registered: "2020-01-22",
    latitude: 27.439824,
    longitude: -85.937465,
    tags: [
      "irure",
      "incididunt",
      "duis",
      "cillum",
      "occaecat",
      "fugiat",
      "laboris",
    ],
    friends: [
      {
        id: 0,
        name: "Francesca Mcneil",
      },
      {
        id: 1,
        name: "Conrad Delaney",
      },
      {
        id: 2,
        name: "Laurel Oneill",
      },
    ],
    greeting: "Hello, Amy Villarreal! You have 6 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "5f5b32e06df0be17ef98b8e3",
    index: 3,
    guid: "cbe089b6-20b1-4d2f-bea5-af7d4955a8f4",
    isActive: false,
    balance: "€2,155",
    personal: "7 / 8",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "green",
    name: "Barnett Mendoza",
    gender: "male",
    company: "IMANT",
    email: "barnettmendoza@imant.com",
    phone: "+1 (934) 492-3325",
    address: "734 Blake Avenue, Comptche, Missouri, 9888",
    about:
      "Tempor enim consectetur nostrud duis pariatur pariatur reprehenderit. Ad proident excepteur eiusmod ex esse qui voluptate aliquip dolore velit amet tempor ex. Voluptate aute ut ipsum pariatur et et eu exercitation cupidatat adipisicing quis elit. Amet reprehenderit ut qui qui id irure elit Lorem dolore. Laborum laborum cillum cupidatat ea ea cupidatat veniam ullamco laboris ex pariatur Lorem sint pariatur. In ut voluptate Lorem do dolore incididunt.\r\n",
    registered: "2020-08-23",
    latitude: 71.46524,
    longitude: -85.336164,
    tags: ["in", "in", "fugiat", "consectetur", "eiusmod", "ad", "velit"],
    friends: [
      {
        id: 0,
        name: "Monroe Mcknight",
      },
      {
        id: 1,
        name: "Lenora Mathis",
      },
      {
        id: 2,
        name: "Henry Wheeler",
      },
    ],
    greeting: "Hello, Barnett Mendoza! You have 9 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "5f5b32e096f8ad938e1587a1",
    index: 4,
    guid: "7869f6c1-0202-4479-a717-39d2676fffcf",
    isActive: true,
    balance: "€2,446",
    personal: "5 / 8",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "green",
    name: "Freda Dalton",
    gender: "female",
    company: "SPACEWAX",
    email: "fredadalton@spacewax.com",
    phone: "+1 (953) 543-3676",
    address: "300 Elmwood Avenue, Brooktrails, Rhode Island, 2624",
    about:
      "Mollit dolor fugiat nostrud irure consequat incididunt officia. Nulla duis ut id magna eu amet irure qui qui consequat tempor quis nisi amet. Consectetur eu est deserunt ex qui cillum.\r\n",
    registered: "2020-04-06",
    latitude: -57.264792,
    longitude: 69.727306,
    tags: [
      "consectetur",
      "minim",
      "sit",
      "reprehenderit",
      "ex",
      "elit",
      "sint",
    ],
    friends: [
      {
        id: 0,
        name: "Bruce Meyers",
      },
      {
        id: 1,
        name: "Key Clark",
      },
      {
        id: 2,
        name: "Patel Buckner",
      },
    ],
    greeting: "Hello, Freda Dalton! You have 6 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "5f5b32e01b39fd9b4367ef39",
    index: 5,
    guid: "429a97ca-836a-4fdd-aa28-ea8326a52dd0",
    isActive: true,
    balance: "€1,414",
    personal: "6 / 8",
    picture: "http://placehold.it/32x32",
    age: 33,
    eyeColor: "blue",
    name: "Jenna Cardenas",
    gender: "female",
    company: "ARTIQ",
    email: "jennacardenas@artiq.com",
    phone: "+1 (952) 546-2299",
    address: "495 Fayette Street, Bourg, California, 1157",
    about:
      "Esse aute magna reprehenderit cupidatat eiusmod consequat sint. Dolore commodo aliqua sit exercitation ea minim. Laborum deserunt dolor cupidatat enim excepteur reprehenderit ut voluptate laboris cillum. Exercitation nostrud elit sit esse eu excepteur reprehenderit. Qui laborum duis aliquip ullamco laboris nisi ipsum deserunt et. Ea nostrud ad proident in amet qui in cupidatat.\r\n",
    registered: "2020-05-14",
    latitude: -65.884183,
    longitude: -143.391893,
    tags: ["Lorem", "magna", "Lorem", "ut", "est", "eu", "nostrud"],
    friends: [
      {
        id: 0,
        name: "Rosalinda Potts",
      },
      {
        id: 1,
        name: "Rochelle Rogers",
      },
      {
        id: 2,
        name: "Coleen Lawson",
      },
    ],
    greeting: "Hello, Jenna Cardenas! You have 1 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "5f5b32e0601201f603b21402",
    index: 6,
    guid: "794464ef-1d98-4436-9ee5-6752dd95d23c",
    isActive: false,
    balance: "€1,873",
    personal: "6 / 8",
    picture: "http://placehold.it/32x32",
    age: 28,
    eyeColor: "blue",
    name: "Sharon Giles",
    gender: "female",
    company: "HOMELUX",
    email: "sharongiles@homelux.com",
    phone: "+1 (849) 567-3179",
    address: "945 Cedar Street, Vernon, Massachusetts, 4796",
    about:
      "Deserunt adipisicing do irure cillum culpa tempor sit dolore. Cillum voluptate laborum laborum officia. Laborum eiusmod adipisicing Lorem incididunt. Nostrud veniam proident laborum quis esse aliqua ad in magna cupidatat deserunt consectetur.\r\n",
    registered: "2020-08-02",
    latitude: -8.329042,
    longitude: -124.720208,
    tags: [
      "dolore",
      "non",
      "aliqua",
      "deserunt",
      "voluptate",
      "adipisicing",
      "commodo",
    ],
    friends: [
      {
        id: 0,
        name: "Katy Levine",
      },
      {
        id: 1,
        name: "Chase Zimmerman",
      },
      {
        id: 2,
        name: "Rhoda Hill",
      },
    ],
    greeting: "Hello, Sharon Giles! You have 4 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "5f5b32e014453beeae711b14",
    index: 7,
    guid: "47ced639-cf8d-4748-96a1-1e351c854c92",
    isActive: false,
    balance: "€2,574",
    personal: "5 / 8",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "brown",
    name: "Murray Bond",
    gender: "male",
    company: "CENTICE",
    email: "murraybond@centice.com",
    phone: "+1 (822) 488-3885",
    address: "380 Alice Court, Fowlerville, North Dakota, 3579",
    about:
      "Voluptate minim esse adipisicing irure esse laboris ipsum eu voluptate. Cupidatat non cillum enim sint reprehenderit cillum reprehenderit enim proident et non do. Eiusmod exercitation excepteur in non amet irure eu laboris. Aliquip laboris ad sunt magna amet. Esse eiusmod deserunt mollit esse ea mollit aliqua pariatur esse irure anim irure. Sunt sunt sunt magna voluptate occaecat velit exercitation enim laborum sit. Dolor nisi laborum consectetur tempor fugiat sint nulla esse sit.\r\n",
    registered: "2020-07-05",
    latitude: -25.229652,
    longitude: -26.662809,
    tags: ["quis", "ex", "eu", "culpa", "amet", "dolor", "sunt"],
    friends: [
      {
        id: 0,
        name: "Ivy Hood",
      },
      {
        id: 1,
        name: "Brock Day",
      },
      {
        id: 2,
        name: "Reid Heath",
      },
    ],
    greeting: "Hello, Murray Bond! You have 9 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "5f5b32e01da06e012af973ed",
    index: 8,
    guid: "b99713fb-2184-4771-92ca-f5bdc577f34a",
    isActive: false,
    balance: "€3,742",
    personal: "4 / 8",
    picture: "http://placehold.it/32x32",
    age: 40,
    eyeColor: "blue",
    name: "Fox Chase",
    gender: "male",
    company: "SULTRAX",
    email: "foxchase@sultrax.com",
    phone: "+1 (890) 487-3754",
    address: "638 Louis Place, Cumminsville, Maryland, 9633",
    about:
      "Velit eiusmod nisi est aliqua amet nulla ullamco sunt deserunt adipisicing aute voluptate. Dolor pariatur laboris consectetur mollit aute sit eiusmod aliqua consectetur in. Enim cupidatat adipisicing ea sunt voluptate tempor pariatur deserunt tempor. Esse voluptate laboris enim excepteur id. Voluptate Lorem mollit ex enim voluptate. Officia laboris aute adipisicing esse labore amet ea reprehenderit nisi non. Reprehenderit aute et amet deserunt veniam veniam id duis sunt.\r\n",
    registered: "2020-06-27",
    latitude: -88.74987,
    longitude: -15.702048,
    tags: [
      "cillum",
      "incididunt",
      "esse",
      "exercitation",
      "enim",
      "et",
      "amet",
    ],
    friends: [
      {
        id: 0,
        name: "Acosta Fischer",
      },
      {
        id: 1,
        name: "Wade Puckett",
      },
      {
        id: 2,
        name: "Nichole Stevenson",
      },
    ],
    greeting: "Hello, Fox Chase! You have 1 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "5f5b32e08271f3e994294a06",
    index: 9,
    guid: "0d33128b-9417-4539-bfbf-71ee9eeccf7e",
    isActive: false,
    balance: "€1,725",
    personal: "3 / 8",
    picture: "http://placehold.it/32x32",
    age: 29,
    eyeColor: "green",
    name: "Buchanan Watson",
    gender: "male",
    company: "JETSILK",
    email: "buchananwatson@jetsilk.com",
    phone: "+1 (985) 410-2626",
    address: "478 Lancaster Avenue, Bradenville, New Mexico, 3844",
    about:
      "Velit sunt eu ad labore. Enim sit commodo culpa do irure id sunt adipisicing esse velit. Aute sit pariatur mollit est amet minim ut deserunt cupidatat id sint. Voluptate incididunt dolor anim dolore reprehenderit anim ad deserunt proident sunt officia. Dolore cillum qui aliqua pariatur ipsum reprehenderit qui dolor.\r\n",
    registered: "2020-01-31",
    latitude: -19.379063,
    longitude: 47.908924,
    tags: ["est", "dolore", "consequat", "minim", "tempor", "amet", "tempor"],
    friends: [
      {
        id: 0,
        name: "Leanna Matthews",
      },
      {
        id: 1,
        name: "Middleton Donovan",
      },
      {
        id: 2,
        name: "Tamera Mays",
      },
    ],
    greeting: "Hello, Buchanan Watson! You have 9 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "5f5b32e04ef445bd31c6fa26",
    index: 10,
    guid: "141dbf47-fd9d-46c2-9f5b-8f8c6eacb4f7",
    isActive: true,
    balance: "€3,007",
    personal: "3 / 8",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "green",
    name: "Catherine Vazquez",
    gender: "female",
    company: "EARTHWAX",
    email: "catherinevazquez@earthwax.com",
    phone: "+1 (869) 600-3454",
    address: "287 Wolf Place, Ebro, North Carolina, 9577",
    about:
      "In dolore sint reprehenderit nostrud adipisicing minim commodo cupidatat Lorem nisi commodo occaecat ex. Excepteur veniam eu aute magna sit ut excepteur id labore officia duis ullamco cillum. Lorem excepteur cupidatat Lorem sunt anim incididunt laboris laborum voluptate esse cillum eu eiusmod. Veniam sint dolore eiusmod et ut duis velit pariatur adipisicing eu ut quis ut sunt. Do reprehenderit anim est laborum consequat deserunt et id Lorem adipisicing in eiusmod reprehenderit consectetur. Occaecat ad esse velit do eiusmod ad in irure. Dolor excepteur officia proident elit officia amet sit nostrud ipsum aliquip.\r\n",
    registered: "2020-03-26",
    latitude: -76.062851,
    longitude: -13.027117,
    tags: ["ipsum", "irure", "magna", "irure", "ullamco", "eu", "amet"],
    friends: [
      {
        id: 0,
        name: "Mcgee Wilcox",
      },
      {
        id: 1,
        name: "Lana Avila",
      },
      {
        id: 2,
        name: "Wolf Navarro",
      },
    ],
    greeting: "Hello, Catherine Vazquez! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "5f5b32e0721483bc5c01cd21",
    index: 11,
    guid: "ff8a6d2f-323d-4438-9979-121e365a5cf6",
    isActive: false,
    balance: "€3,319",
    personal: "3 / 8",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "brown",
    name: "Palmer Alford",
    gender: "male",
    company: "EXOSIS",
    email: "palmeralford@exosis.com",
    phone: "+1 (841) 469-3301",
    address: "327 Dekoven Court, Hickory, Virginia, 6958",
    about:
      "Nostrud consequat proident reprehenderit adipisicing anim mollit adipisicing mollit excepteur minim. Aute nulla quis officia mollit incididunt qui eiusmod eu incididunt consequat excepteur non aliquip exercitation. Dolor nisi incididunt nulla velit laborum. Elit nostrud laborum esse velit ut excepteur minim laboris in. Qui sint ad duis velit Lorem nulla. Qui in sunt aliquip tempor incididunt eiusmod eu veniam mollit.\r\n",
    registered: "2020-01-03",
    latitude: 48.7436,
    longitude: -99.497124,
    tags: ["consectetur", "in", "veniam", "anim", "elit", "elit", "duis"],
    friends: [
      {
        id: 0,
        name: "Oliver Mcguire",
      },
      {
        id: 1,
        name: "Carey Little",
      },
      {
        id: 2,
        name: "Lula Workman",
      },
    ],
    greeting: "Hello, Palmer Alford! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "5f5b32e044a8cba21b1f8e45",
    index: 12,
    guid: "38a6dfc4-d484-4785-9c73-166a121403b0",
    isActive: true,
    balance: "€2,587",
    personal: "5 / 8",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "brown",
    name: "Myrna Sosa",
    gender: "female",
    company: "EXTRO",
    email: "myrnasosa@extro.com",
    phone: "+1 (988) 425-3812",
    address: "298 Adler Place, Davenport, Marshall Islands, 8116",
    about:
      "Est pariatur excepteur ex non qui consequat velit voluptate in. Voluptate in amet deserunt amet. Nostrud minim in occaecat pariatur dolore occaecat excepteur proident voluptate reprehenderit voluptate occaecat adipisicing. Non id consequat esse proident non ea ea. Adipisicing sint incididunt aliqua officia dolore. Officia esse consequat adipisicing duis fugiat ut qui ullamco pariatur aliqua ut laboris.\r\n",
    registered: "2020-05-29",
    latitude: 81.536514,
    longitude: 177.416394,
    tags: ["culpa", "qui", "proident", "laboris", "id", "irure", "magna"],
    friends: [
      {
        id: 0,
        name: "Aisha Raymond",
      },
      {
        id: 1,
        name: "Latonya Bailey",
      },
      {
        id: 2,
        name: "Gaines Barber",
      },
    ],
    greeting: "Hello, Myrna Sosa! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
];
